language: php
services:
  - mysql

env:
php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

matrix:
  include:
    - php: nightly
      env: FORCE_LATEST=1
    - php: 5.5
      dist: trusty
    - php: 5.4
      dist: trusty
    - php: 5.4
      env: PREFER_LOWEST=1
      dist: trusty
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/composer
    - $HOME/.cache/opcache

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - phpenv config-rm xdebug.ini || true;
  - composer validate --strict
  - |
    if [ "$PREFER_LOWEST" = "1" ]; then
      composer update --prefer-lowest;
    elif [ "$FORCE_LATEST" = "1" ]; then
      composer update --ignore-platform-reqs;
    else
      composer update;
    fi;

script:
  - |
    if [ "$CSFIXER" = "1" ]; then
      vendor/bin/php-cs-fixer fix --verbose --dry-run --diff --diff-format=udiff --allow-risky=yes;
    fi;
  - php vendor/bin/phpunit;
