DROP DATABASE IF EXISTS `test`;
CREATE DATABASE `test`;
USE `test`;
CREATE TABLE `test_integers` (`tinyint` TINYINT NOT NULL,
                                     `smallint` SMALLINT NOT NULL,
                                     `mediumint` MEDIUMINT NOT NULL,
                                     `int` INT NOT NULL,
                                     `bigint` BIGINT NOT NULL,
                                     `tinyint_unsigned` TINYINT UNSIGNED NOT NULL,
                                     `smallint_unsigned` SMALLINT UNSIGNED NOT NULL,
                                     `mediumint_unsigned` MEDIUMINT UNSIGNED NOT NULL,
                                     `int_unsigned` INT UNSIGNED NOT NULL,
                                     `bigint_unsigned` BIGINT UNSIGNED NOT NULL,
                                     `int_null` INT NULL,
                                     `int_unsigned_null` INT UNSIGNED NULL,
                                     `int_default_null` INT NULL DEFAULT NULL,
                                     `int_default_12345` INT NOT NULL DEFAULT '12345');
CREATE TABLE `test_strings` (`varchar` VARCHAR(12) NOT NULL,
                             `char` CHAR(34) NOT NULL,
                             `varchar_null` VARCHAR(45) NULL,
                             `char_null` CHAR(67) NULL,
                             `enum` ENUM('abc', 'def') NOT NULL,
                             `enum_null` ENUM('hij', 'klm') NULL,
                             `set` SET('nop', 'qrs') NOT NULL,
                             `set_null` SET('tuv', 'wxyz') NULL);
INSERT INTO `test_strings` (`varchar`, `char`, `varchar_null`, `char_null`, `enum`, `enum_null`, `set`, `set_null`)
                    VALUES ('foo1', 'foo1', NULL, NULL, 'abc', 'hij', 'nop,qrs', 'tuv'),
                           ('foo2', 'foo2', NULL, NULL, 'def', 'klm', 'nop,qrs', 'tuv'),
                           ('foo3', 'foo3', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo4', 'foo4', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo5', 'foo5', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo6', 'foo6', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo7', 'foo7', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo8', 'foo8', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo9', 'foo9', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo10', 'foo10', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo11', 'foo1', NULL, NULL, 'abc', 'hij', 'nop,qrs', 'tuv'),
                           ('foo12', 'foo2', NULL, NULL, 'def', 'klm', 'nop,qrs', 'tuv'),
                           ('foo13', 'foo3', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo14', 'foo4', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo15', 'foo5', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo16', 'foo6', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo17', 'foo7', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo18', 'foo8', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo19', 'foo9', NULL, NULL, 'abc', NULL, 'qrs', NULL),
                           ('foo20', 'foo10', NULL, NULL, 'abc', NULL, 'qrs', NULL);